# Generated by Django 5.1.7 on 2025-04-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='radius_km',
            field=models.FloatField(default=25),
        ),
    ]
