# Generated by Django 5.1.7 on 2025-04-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='banner_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
