# Generated by Django 5.1.7 on 2025-04-21 12:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_name_alter_users_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='banner_image',
            field=users.models.Base64ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=users.models.Base64ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
