# Generated by Django 4.2.8 on 2025-04-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('finance', 'Finance'), ('business', 'Business')], max_length=50)),
            ],
        ),
    ]
