"""



Django settings for hustler project. 







Generated by 'django-admin startproject' using Django 4.2.5.







For more information on this file, see



https://docs.djangoproject.com/en/4.2/topics/settings/







For the full list of settings and their values, see



https://docs.djangoproject.com/en/4.2/ref/settings/



"""







from pathlib import Path

#from firebase_admin import initialize_app

import os

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',  # Custom class for debug messages
    messages.INFO: 'alert-info',    # Bootstrap info color
    messages.SUCCESS: 'alert-success',  # Bootstrap success color
    messages.WARNING: 'alert-warning',  # Bootstrap warning color
    messages.ERROR: 'alert-danger',  # Bootstrap danger color
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.



BASE_DIR = Path(__file__).resolve().parent.parent





import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')






# Quick-start development settings - unsuitable for production



# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/



#FIREBASE_APP = initialize_app()



# SECURITY WARNING: keep the secret key used in production secret!



SECRET_KEY = 'django-insecure-js@cra0$&f@h$7!pp*8i=-k&t=i)k_14+a4-5-5qi2ath1nkd-'







# SECURITY WARNING: don't run with debug turned on in production!



DEBUG = True







# ALLOWED_HOSTS = ['https://hustlersandseekers.co/','hustlersandseekers.co', 'https://staging.hustlersandseekers.co/', 'staging.hustlersandseekers.co']

#ALLOWED_HOSTS = ['82.25.86.49']
#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]


# Channels origin whitelist (optional, Channels 3+)
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost",
#     "http://127.0.0.1",
# ]
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB



CORS_ALLOW_ALL_ORIGINS = True  
# For testing only. Restrict in production.
# CSRF_TRUSTED_ORIGINS = ['127.0.0.1:8000']




# Application definition







INSTALLED_APPS = [



    'django.contrib.admin',
     'csp',



    'django.contrib.auth',



    'django.contrib.contenttypes',



    'django.contrib.sessions',



    'django.contrib.messages',



    'django.contrib.staticfiles',



    'users.apps.UsersConfig',



    # 'category.apps.CategoryConfig',



    # 'subcategory.apps.SubcategoryConfig',



    # 'settings.apps.SettingsConfig',



    # 'home.apps.HomeConfig',



    # 'dashboard.apps.DashboardConfig',



    'rest_framework',



    'rest_framework.authtoken',



    # 'django_rest_passwordreset',


    # 'hustler_role_category',
    'corsheaders',

    'wallet_resume',
    
     'connect',
     'channels',
    # 'fcm_django',
   
    'news',
    'hustler_role_category',

]

ASGI_APPLICATION = 'hustler.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }





FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAAMmfUttw:APA91bFl7CTYHRar2M4KAY_GskDEfApLqawNehtyL7_vjNWsF476TAwT1a3Rf5PNkS2F9D6tTUzC8cShbvRYukWU5STpEkeiiIld0Yd8OnBQLL8heqfYfOeNqjCYJxnh_LNhCwmlx-4P",
    "APP_PREFIX": "com.app.hustlersandseekers",
    "PROJECT_ID": "hustlersandseekers-6d005",
}




MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

   'corsheaders.middleware.CorsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',



    'django.contrib.sessions.middleware.SessionMiddleware',



    'django.middleware.common.CommonMiddleware',



    'django.middleware.csrf.CsrfViewMiddleware',



    'django.contrib.auth.middleware.AuthenticationMiddleware',



    'django.contrib.messages.middleware.MessageMiddleware',



    'django.middleware.clickjacking.XFrameOptionsMiddleware',



]


CORS_ALLOW_ALL_ORIGINS = True 



ROOT_URLCONF = 'hustler.urls'







TEMPLATES = [



    {



        'BACKEND': 'django.template.backends.django.DjangoTemplates',



        'DIRS': [os.path.join(BASE_DIR, 'templates')],



        'APP_DIRS': True,



        'OPTIONS': {



            'context_processors': [



                'django.template.context_processors.debug',



                'django.template.context_processors.request',



                'django.contrib.auth.context_processors.auth',



                'django.contrib.messages.context_processors.messages',



            ],



        },



    },



]







STATIC_URL = '/static/'



MEDIA_URL = '/media/'









STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')







WSGI_APPLICATION = 'hustler.wsgi.application'










# Database



# https://docs.djangoproject.com/en/4.2/ref/settings/#databases







# DATABASES = {



#     'default': {



#         'ENGINE': 'django.db.backends.postgresql',



#         'NAME': 'hustlersseeker_live',



#         'USER': 'hustlersseeker_liveuser',



#         'PASSWORD': '0uSWy6Imexff',



#         'HOST': 'localhost',



#     }



# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}










# Password validation



# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators







AUTH_PASSWORD_VALIDATORS = [



    {



        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',



    },



    {



        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',



    },



    {



        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',



    },



    {



        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',



    },



]











# Internationalization



# https://docs.djangoproject.com/en/4.2/topics/i18n/







LANGUAGE_CODE = 'en-us'







TIME_ZONE = 'UTC'







USE_I18N = True







USE_TZ = True











# Static files (CSS, JavaScript, Images)



# https://docs.djangoproject.com/en/4.2/howto/static-files/















# Default primary key field type



# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

AUTH_USER_MODEL = 'users.Users'

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [

        'rest_framework.authentication.TokenAuthentication',

    ],

}
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'rest_framework.authentication.TokenAuthentication',
    'rest_framework.authentication.SessionAuthentication',
    # 'home.backend.CustomUserBackend', 
]



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Email Backend Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Replace with your preferred backend



EMAIL_PORT = 2525 

EMAIL_USE_TLS = False 

EMAIL_HOST = 'mail.smtp2go.com'

EMAIL_HOST_USER = 'no-reply@hustlersandseekers.co'

EMAIL_HOST_PASSWORD = 'xnF2ep04TiYjXfFI'

ACCOUNT_EMAIL_VERIFICATION = 'none'




