# Generated by Django 5.1.7 on 2025-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('role_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('about_yourself', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='users/role_category/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='users/role_category/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='users/role_category/')),
                ('video', models.FileField(blank=True, null=True, upload_to='users/role_category/')),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True)),
                ('isnta_link', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_link', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=255, null=True)),
                ('yt_link', models.CharField(blank=True, max_length=255, null=True)),
                ('other_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='users/posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
