# Generated by Django 5.1.7 on 2025-04-22 15:33

import hustler_role_category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustler_role_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscategory',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userscategory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userscategory',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userscategory',
            name='image1',
            field=hustler_role_category.models.Base64ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscategory',
            name='image2',
            field=hustler_role_category.models.Base64ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscategory',
            name='image3',
            field=hustler_role_category.models.Base64ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscategory',
            name='is_primary',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='userscategory',
            name='video',
            field=hustler_role_category.models.Base64VideoField(blank=True, null=True),
        ),
    ]
