# Generated by Django 5.2.1 on 2025-05-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustler_role_category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersPosts',
        ),
    ]
