# Generated by Django 5.1.7 on 2025-04-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustler_role_category', '0002_userscategory_latitude_userscategory_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
