# Generated by Django 5.1.7 on 2025-04-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustler_role_category', '0003_alter_userscategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscategory',
            old_name='id',
            new_name='category_id',
        ),
    ]
