# Generated by Django 5.1.7 on 2025-04-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustler_role_category', '0004_rename_id_userscategory_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscategory',
            old_name='category_id',
            new_name='id',
        ),
    ]
